In [18]:
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn import tree
from sklearn import datasets
from sklearn.cross_validation import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier#dejamos todos los valores por default, pero decidimos tener 20 árboles. 
rf = RandomForestClassifier(n_estimators=50)

rf=rf.fit(X_train, Y_train)

print(rf.feature_importances_)


iris = datasets.load_iris()
type(iris)


sklearn.utils.Bunch

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size=0.30, random_state=42)

In [11]:
#Entrenamos el modelo
tree_class = tree.DecisionTreeClassifier(min_samples_leaf=4)
tree_class = tree_class.fit(X_train, Y_train)

In [12]:
prediction = tree_class.predict(X_test)

In [13]:
## matriz de confusión
confusion = confusion_matrix(Y_test, prediction)
confusion

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [14]:
accuracy_score(Y_test, prediction)

1.0

In [17]:

target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(Y_test, prediction, target_names=target_names))

             precision    recall  f1-score   support

    class 0       1.00      1.00      1.00        19
    class 1       1.00      1.00      1.00        13
    class 2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        45



In [19]:
#dejamos todos los valores por default, pero decidimos tener 20 árboles. 
rf = RandomForestClassifier(n_estimators=50)

rf=rf.fit(X_train, Y_train)

print(rf.feature_importances_)

[ 0.09012009  0.0471873   0.43968779  0.42300482]


In [20]:
prediction_rf = rf.predict(X_test)

In [21]:

confusion_rf = confusion_matrix(Y_test, prediction_rf)
confusion_rf

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [22]:
accuracy_score(Y_test, prediction_rf)

1.0

In [23]:
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(Y_test, prediction_rf, target_names=target_names))

             precision    recall  f1-score   support

    class 0       1.00      1.00      1.00        19
    class 1       1.00      1.00      1.00        13
    class 2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        45



Tienen la misma precision RF y los arboles. Perfecta de 100%.